[package]
name = "icegen"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.18", features = ["cargo", "derive"] }

anyhow = "1.0.80"

nom = "7.1.3"

indoc = "2.0.5"
